name: Publish reporter image
on:
  push:
    tags:
    - v*.*.*
  workflow_dispatch:
jobs:
  publish-image:
    name: Publish image
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: 'Build Inventory Image'
      run: |
        docker build . --tag ghcr.io/${{ github.repository_owner }}/pypsa-reporter:latest --file docker/reporter/Dockerfile
        
    - name: 'Push Inventory Image'
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/pypsa-reporter:latest